[package]
name = "rust_intellij_templates"
version = "0.1.0"
authors = ["Michael Phelps <michael.phelps@nottheswimmer.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
